voyc.courselist = [
	{ id:'grkybd', section: 'Grammar', course: 'Keyboard', level: 9, },
	{ id:'gralph', section: 'Grammar', course: 'Alphabet', level: 7, },
	{ id:'grcons', section: 'Grammar', course: 'Consonants', level: 5, },
	{ id:'grvowl', section: 'Grammar', course: 'Vowels', level: 3, },
	{ id:'grtone', section: 'Grammar', course: 'Tones', level: 2, },
	{ id:'grsynt', section: 'Grammar', course: 'Syntax', level: 1, },
	{ id:'cohelo', section: 'Conversation', course: 'Hello Goodbye', level: 8,},
	{ id:'cothnk', section: 'Conversation', course: 'Thank You', level: 6,},
	{ id:'coname', section: 'Conversation', course: 'Names', level: 3,},
	{ id:'cosign', section: 'Conversation', course: 'Signs', level: 3,},
	{ id:'colaun', section: 'Conversation', course: 'Laundry', level: 1,},
	{ id:'cohous', section: 'Conversation', course: 'Housing', level: 1,},
	{ id:'cowher', section: 'Conversation', course: 'Where', level: 1,},
	{ id:'cowhen', section: 'Conversation', course: 'When', level: 1,},
	{ id:'cowhoo', section: 'Conversation', course: 'Who', level: 0,},
	{ id:'cofmly', section: 'Conversation', course: 'Family', level: 0,},
	{ id:'comrkt', section: 'Conversation', course: 'Market', level: 0,},
	{ id:'cofood', section: 'Conversation', course: 'Food', level: 0,},
	{ id:'coclot', section: 'Conversation', course: 'Clothing', level: 0,},
	{ id:'comenu', section: 'Conversation', course: 'Menu', level: 0,},
	{ id:'comedi', section: 'Conversation', course: 'Medical', level: 0,},
	{ id:'coromc', section: 'Conversation', course: 'Romance/Sex', level: 0,},
	{ id:'enhist', section: 'Encyclopedia', course: 'History', level: 0,},
	{ id:'engeog', section: 'Encyclopedia', course: 'Geography', level: 0,},
	{ id:'enbuda', section: 'Encyclopedia', course: 'Buddhism', level: 0,},
	{ id:'enflow', section: 'Encyclopedia', course: 'Flowers', level: 0,},
	{ id:'encmai', section: 'Encyclopedia', course: 'Chiang Mai', level: 0,},
	{ id:'sobdss', section: 'Songs', course: 'Bird: Sabai Sabai', level: 0,},
	{ id:'sobabu', section: 'Songs', course: 'Bird+Atom: Beyond Universe', level: 0,},
	{ id:'socilu', section: 'Songs', course: 'พลพล: ให้ ฉัน รัก เธอ ได้ ไหม', level: 0,},
	{ id:'mnbk01', section: 'Maanii', course: 'Book 1', level: 0,},
	{ id:'mnbk02', section: 'Maanii', course: 'Book 2', level: 0,},
	{ id:'mnbk03', section: 'Maanii', course: 'Book 3', level: 0,}
];
