if (!voyc.thai) { voyc.thai = {}; }
voyc.thai.courselist = [
	{ id:'grkybd', section: 'Grammar', course: 'Keyboard' },
	{ id:'gralph', section: 'Grammar', course: 'Alphabet' },
	{ id:'grcons', section: 'Grammar', course: 'Consonants' },
	{ id:'grvowl', section: 'Grammar', course: 'Vowels' },
	{ id:'grtone', section: 'Grammar', course: 'Tones' },
	{ id:'grsynt', section: 'Grammar', course: 'Syntax' },
	{ id:'auda01', section: 'AUA', course: 'Nouns and Adjectives' },
	{ id:'cohelo', section: 'Conversation', course: 'Hello Goodbye'},
	{ id:'cothnk', section: 'Conversation', course: 'Thank You'},
	{ id:'coname', section: 'Conversation', course: 'Names'},
	{ id:'cosign', section: 'Conversation', course: 'Signs'},
	{ id:'colaun', section: 'Conversation', course: 'Laundry'},
	{ id:'cohous', section: 'Conversation', course: 'Housing'},
	{ id:'cowher', section: 'Conversation', course: 'Where'},
	{ id:'cowhen', section: 'Conversation', course: 'When'},
	{ id:'cowhoo', section: 'Conversation', course: 'Who'},
	{ id:'cofmly', section: 'Conversation', course: 'Family'},
	{ id:'comrkt', section: 'Conversation', course: 'Market'},
	{ id:'cofood', section: 'Conversation', course: 'Food'},
	{ id:'coclot', section: 'Conversation', course: 'Clothing'},
	{ id:'comenu', section: 'Conversation', course: 'Menu'},
	{ id:'comedi', section: 'Conversation', course: 'Medical'},
	{ id:'coromc', section: 'Conversation', course: 'Romance/Sex'},
	{ id:'enhist', section: 'Encyclopedia', course: 'History'},
	{ id:'engeog', section: 'Encyclopedia', course: 'Geography'},
	{ id:'enbuda', section: 'Encyclopedia', course: 'Buddhism'},
	{ id:'enflow', section: 'Encyclopedia', course: 'Flowers'},
	{ id:'encmai', section: 'Encyclopedia', course: 'Chiang Mai'},
	{ id:'sobdss', section: 'Songs', course: 'Bird: Sabai Sabai'},
	{ id:'sobabu', section: 'Songs', course: 'Bird+Atom: Beyond Universe'},
	{ id:'socilu', section: 'Songs', course: 'พลพล: ให้ ฉัน รัก เธอ ได้ ไหม'},
	{ id:'mabk01', section: 'Maanii', course: 'Book 1'},
	{ id:'mabk02', section: 'Maanii', course: 'Book 2'},
	{ id:'mabk03', section: 'Maanii', course: 'Book 3'}
];
