
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ก','kg'  ,''   ,'m',' ',	U&'\0e01', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ข','k'   ,''   ,'h',' ',	U&'\0e02', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'o' ,'ฃ','s'   ,''   ,' ',' ',	U&'\0e03', 'obsolete' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ค','k'   ,''   ,'l',' ',	U&'\0e04', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'o' ,'ฅ',''    ,''   ,' ',' ',	U&'\0e05', 'obsolete' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ฆ','k'   ,'ค'  ,' ','k',	U&'\0e06', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ง','ng'  ,''   ,'l','s',	U&'\0e07', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'จ','j'   ,''   ,'m',' ',	U&'\0e08', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ฉ','ch'  ,''   ,'h',' ',	U&'\0e09', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ช','ch'  ,''   ,'l',' ',	U&'\0e0A', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ซ','s'   ,''   ,'l',' ',	U&'\0e0B', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ฌ','ch'  ,'ช'  ,' ','k',	U&'\0e0C', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ญ','y'   ,'ย'  ,' ','k',	U&'\0e0D', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ฎ','d'   ,'ด'  ,' ','k',	U&'\0e0E', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ฏ','dt'  ,'ต'  ,' ','k',	U&'\0e0F', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ฐ','t'   ,'ถ'  ,' ','k',	U&'\0e10', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ฑ','t'   ,'ท'  ,' ','k',	U&'\0e11', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ฒ','t'   ,'ท'  ,' ','k',	U&'\0e12', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ณ','n'   ,'น'  ,' ','k',	U&'\0e13', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ด','d'   ,''   ,'m',' ',	U&'\0e14', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ต','dt'  ,''   ,'m',' ',	U&'\0e15', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ถ','t'   ,''   ,'h',' ',	U&'\0e16', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ท','t'   ,''   ,'l',' ',	U&'\0e17', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ธ','t'   ,'ท'  ,' ','k',	U&'\0e18', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'น','n'   ,''   ,'l','s',	U&'\0e19', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'บ','b'   ,''   ,'m',' ',	U&'\0e1A', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ป','bp'  ,''   ,'m',' ',	U&'\0e1B', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ผ','p'   ,''   ,'h',' ',	U&'\0e1C', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ฝ','f'   ,''   ,'h',' ',	U&'\0e1D', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'พ','p'   ,''   ,'l',' ',	U&'\0e1E', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ฟ','f'   ,''   ,'l',' ',	U&'\0e1F', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ภ','p'   ,'พ'  ,' ','k',	U&'\0e20', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ม','m'   ,''   ,'l','s',	U&'\0e21', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ย','y'   ,''   ,'l','s',	U&'\0e22', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ร','r'   ,''   ,'l','s',	U&'\0e23', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'b' ,'ฤ','pri' ,''   ,' ',' ',	U&'\0e24', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ล','l'   ,''   ,'l','s',	U&'\0e25', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'u' ,'ฦ',''    ,''   ,' ',' ',	U&'\0e26', 'unknown' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ว','w'   ,''   ,'l','s',	U&'\0e27', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ศ','s'   ,'ส'  ,' ','k',	U&'\0e28', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ษ','s'   ,'ส'  ,' ','k',	U&'\0e29', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ส','s'   ,''   ,'h',' ',	U&'\0e2A', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ห','h'   ,''   ,'h',' ',	U&'\0e2B', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ฬ','l'   ,'ล'  ,' ','k',	U&'\0e2C', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'อ','aw'  ,''   ,'m',' ',	U&'\0e2D', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'c' ,'ฮ','h'   ,''   ,'l',' ',	U&'\0e2E', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'s' ,'ฯ','.'   ,''   ,' ',' ',	U&'\0e2F', 'abbrevia' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'v' ,'ะ','a'   ,''   ,'s',' ',	U&'\0e30', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'v' ,'ั' ,'a'   ,''   ,'s',' ',	U&'\0e31', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'v' ,'า','aa'  ,''   ,'o',' ',	U&'\0e32', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'b' ,'ำ','am'  ,''   ,'o','d',	U&'\0e33', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'v' ,'ิ','i'   ,''   ,'s','d',	U&'\0e34', '' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'v' ,'ี','ii'  ,''   ,'o','d',	U&'\0e35', ''            );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'v' ,'ึ','ʉ'   ,''   ,'s','d',	U&'\0e36', ''            );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'v' ,'ื','ʉʉ'  ,''   ,'o','d',	U&'\0e37', ''            );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'v' ,'ุ','u'   ,''   ,'s','d',	U&'\0e38', ''            );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'v' ,'ู','uu'  ,''   ,'o','d',	U&'\0e39', ''            );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'u' ,'ฺ',''    ,''   ,' ','d',	U&'\0e3A', 'unknown'     );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'s' ,'฿','baht',''   ,' ',' ',	U&'\0e3F', 'baht'        );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'v' ,'เ','e'   ,''   ,'s',' ',	U&'\0e40', ''            );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'v' ,'แ','ee'  ,''   ,'o',' ',	U&'\0e41', ''            );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'v' ,'โ','o'   ,''   ,'o',' ',	U&'\0e42', ''            );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'v' ,'ใ','ai'  ,''   ,'o',' ',	U&'\0e43', ''            );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'v' ,'ไ','ai'  ,''   ,'o',' ',	U&'\0e44', ''            );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'u' ,'ๅ',''    ,''   ,' ',' ',	U&'\0e45', 'unknown'     );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'s' ,'ๆ','rept','' ,' ',' ',	U&'\0e46', 'repeat'      );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'v' ,'็','e'   ,''   ,' ','d',	U&'\0e47', ''            );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'t' ,'่',''    ,''   ,' ','d',	U&'\0e48', 'tone 1'      );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'t' ,'้',''    ,''   ,' ','d',	U&'\0e49', 'tone 2'      );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'t' ,'๊',''    ,''   ,' ','d',	U&'\0e4A', 'tone 3'      );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'t' ,'๋',''    ,''   ,' ','d',	U&'\0e4B', 'tone 4'      );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'t' ,'์','slnt','' ,' ','d',	U&'\0e4C', 'tone silent' );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'u' ,'ํ',''    ,''   ,' ','d',	U&'\0e4D', 'unknown'     );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'u' ,'๎',''    ,''   ,' ','d',	U&'\0e4E', 'unknown'     );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'d' ,'๐','0'   ,''   ,' ',' ',	U&'\0e50', ''            );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'d' ,'๑','1'   ,''   ,' ',' ',	U&'\0e51', ''            );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'d' ,'๒','2'   ,''   ,' ',' ',	U&'\0e52', ''            );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'d' ,'๓','3'   ,''   ,' ',' ',	U&'\0e53', ''            );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'d' ,'๔','4'   ,''   ,' ',' ',	U&'\0e54', ''            );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'d' ,'๕','5'   ,''   ,' ',' ',	U&'\0e55', ''            );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'d' ,'๖','6'   ,''   ,' ',' ',	U&'\0e56', ''            );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'d' ,'๗','7'   ,''   ,' ',' ',	U&'\0e57', ''            );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'d' ,'๘','8'   ,''   ,' ',' ',	U&'\0e58', ''            );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'d' ,'๙','9'   ,''   ,' ',' ',	U&'\0e59', ''            );
insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'u' ,'๚',''    ,''   ,' ',' ',	U&'\0e5A', 'unknown'     );

insert into mai.thaidict (source, level, numdef, type, pos, thai, eng, reference, class, subclass, unicode, details) values (0 , 10 ,1 ,'g' ,'u' ,'๛',''    ,''   ,' ',' ',	U&'\0e5B', 'unknown'     );
