/**
**/
voyc.thai.course.gr.tone = {
        section:'grammar',
        course:'Tones',
}

voyc.thai.course.gr.tone.wh = {
        id:'grtonewh',
        prereq:true,
        postreq:false,
        algorithm: 'progressive',
        primaryDictType: 'word',
	title:'mid-class live',
        glyph:[],
        word:[
		'ใจ',
		'ดี',
		'เอา',
		'กิน',
		'ดม',
		'มวย',
		'ฟัง',
		'ดวง',
		'คน',
		'เดิน',
		'บน',
		'เติม',
		'ปืน',
		'เป็น',
		'เบา',
		'ไกล',
	],
        phrase:[],
};

voyc.thai.course.gr.tone.ye = {
        id:'grtoneye',
	title:'high-class live',
        prereq:true,
        postreq:false,
        algorithm: 'progressive',
        primaryDictType: 'word',
        glyph:[],
        word:[
		'เขา',
		'ผม',
		'ฉัน',
		'ของ',
		'หัว',
		'เห็น',
		'ขม',
		'ถือ',
		'ขน',
		'สวน',
		'ฝัน',
		'ฝน',
	],
        phrase:[],
};

voyc.thai.course.gr.tone.or = {
        id:'grtoneor',
	title:'low-class live',
        prereq:true,
        postreq:false,
        algorithm: 'progressive',
        primaryDictType: 'word',
        glyph:[],
        word:[
		'รู',
		'ยิน',
		'คุณ',
		'ใน',
		'เพลง',
		'มัน',
		'ยืน',
		'รวย',
		'คืน',
		'นวด',
		'มือ',
		'วัน',
		'นม',
		'ลม',
		'เค็ม',
		'คือ',
		'ฟัน',
		'ลง',
		'แพง',
		'หรือ',
	],
        phrase:[],
};

voyc.thai.course.gr.tone.gr = {
        id:'grtonegr',
	title:'mid-class dead',
        prereq:true,
        postreq:false,
        algorithm: 'progressive',
        primaryDictType: 'word',
        glyph:[],
        word:[
		'เบิก',
		'ปวด',
		'กัด',
		'จบ',
		'ปลวก',
		'ตก',
		'จัก',
		'กับ',
		'จบ',
		'เจ็บ',
		'อีก',
		'เปิด',
	],
        phrase:[],
};
voyc.thai.course.gr.tone.bl = {
        id:'grtonebl',
	title:'high-class dead',
        prereq:true,
        postreq:false,
        algorithm: 'progressive',
        primaryDictType: 'word',
        glyph:[],
        word:[
		'สด',
		'เห็ด',
		'อบ',
		'ผัด',
		'ผัก',
		'อยาก',
		'ถูก',
	],
        phrase:[],
};
voyc.thai.course.gr.tone.pu = {
        id:'grtonepu',
	title:'low-class dead short',
        prereq:true,
        postreq:false,
        algorithm: 'progressive',
        primaryDictType: 'word',
        glyph:[],
        word:[
		'วัด',
		'เปิด',
		'ลบ',
		'ลด',
		'มด',
		'นัด',
		'พบ',
		'ครับ',
		'รถ',
	],
        phrase:[],
};
voyc.thai.course.gr.tone.re = {
        id:'grtonere',
	title:'low-class dead long',
        prereq:true,
        postreq:false,
        algorithm: 'progressive',
        primaryDictType: 'word',
        glyph:[],
        word:[
		'ลวก',
		'มืด',
		'พูด',
		'ชอบ',
		'เงียบ',
		'ยาก',
		'มาก',
	],
        phrase:[],
};
voyc.thai.course.gr.tone.br = {
        id:'grtonebr',
	title:'mark 1',
        prereq:true,
        postreq:false,
        algorithm: 'progressive',
        primaryDictType: 'word',
        glyph:[],
        word:[
		// mid
		'ดื่ม',
		'อื่น',
		// high
		'ชื่อ',
		'ส่าย',
		'ใหม่',
		// low
		'เพิ่ม',
		'ไม่',
		'ที่',
		'นี่',
		'นั่ง',
		'แม่',
		'พ่อ',
		'เล่น',
		'ง่าย',
		'แย่',
	],
        phrase:[],
};
voyc.thai.course.gr.tone.bk = {
        id:'grtonebk',
	title:'mark 2',
        prereq:true,
        postreq:false,
        algorithm: 'progressive',
        primaryDictType: 'word',
        glyph:[],
        word:[
		// mid
		'ได้',
		'ด้วย',
		'ใกล้',
		// high
		'เข้า',
		'ขึ้น',
		// low
		'รู้',
		'น้ำ',
		'ช้า',
		'เท้า',
		'น้อย',
	],
        phrase:[],
};
voyc.onCourseLoaded('grtone');
